// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PiedraPapelOTijera.Data;

#nullable disable

namespace PiedraPapelOTijera.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220328210111_InicioBase")]
    partial class InicioBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PiedraPapelOTijera.Data.Model.InfoRondas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Ganador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ronda")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("IRondas");
                });
#pragma warning restore 612, 618
        }
    }
}
