// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PiedraPapelOTijera.Data;

#nullable disable

namespace PiedraPapelOTijera.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220409012405_saveDB")]
    partial class saveDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PiedraPapelOTijera.Data.Model.Elemento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Elemento");
                });

            modelBuilder.Entity("PiedraPapelOTijera.Data.Model.Gana", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ElementoId")
                        .HasColumnType("int");

                    b.Property<int>("GanaContraId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ElementoId");

                    b.HasIndex("GanaContraId");

                    b.ToTable("Gana");
                });

            modelBuilder.Entity("PiedraPapelOTijera.Data.Model.InfoRondas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("Elemento1Id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Elemento2Id")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("ElementoGanador")
                        .HasColumnType("int");

                    b.Property<int>("PartidaId")
                        .HasColumnType("int");

                    b.Property<int>("Ronda")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Elemento1Id");

                    b.HasIndex("Elemento2Id");

                    b.HasIndex("PartidaId");

                    b.ToTable("Rondas");
                });

            modelBuilder.Entity("PiedraPapelOTijera.Data.Model.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Ganador")
                        .HasColumnType("int");

                    b.Property<string>("Jugador1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jugador2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("PiedraPapelOTijera.Data.Model.Gana", b =>
                {
                    b.HasOne("PiedraPapelOTijera.Data.Model.Elemento", "Elemento")
                        .WithMany()
                        .HasForeignKey("ElementoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PiedraPapelOTijera.Data.Model.Elemento", "GanaContra")
                        .WithMany()
                        .HasForeignKey("GanaContraId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Elemento");

                    b.Navigation("GanaContra");
                });

            modelBuilder.Entity("PiedraPapelOTijera.Data.Model.InfoRondas", b =>
                {
                    b.HasOne("PiedraPapelOTijera.Data.Model.Elemento", "Elemento1")
                        .WithMany("RondasE1")
                        .HasForeignKey("Elemento1Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PiedraPapelOTijera.Data.Model.Elemento", "Elemento2")
                        .WithMany("RondasE2")
                        .HasForeignKey("Elemento2Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PiedraPapelOTijera.Data.Model.Partida", "Partida")
                        .WithMany("Rondas")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Elemento1");

                    b.Navigation("Elemento2");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("PiedraPapelOTijera.Data.Model.Elemento", b =>
                {
                    b.Navigation("RondasE1");

                    b.Navigation("RondasE2");
                });

            modelBuilder.Entity("PiedraPapelOTijera.Data.Model.Partida", b =>
                {
                    b.Navigation("Rondas");
                });
#pragma warning restore 612, 618
        }
    }
}
